apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: hubui-nextjs-template
  title: HubUI Next.js Template
  description: Template for Next.js projects inside HubUI

spec:
  owner: backstage/lego-core
  type: service
  parameters:
    - title: Project information
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - git.pipefy.net
        owner:
          title: Owner Team
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
    - id: debug-log
      name: Debug
      action: debug:log
      input:
        listWorkspace: true
    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}
    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

  # output:
  #   remoteUrl: ${{ steps.publish.output.remoteUrl }}
  #   entityRef: ${{ steps.register.output.entityRef }}
